name: 🛠️ Update Contributors

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build and generate contributors
        run: |
          yarn build
          yarn generate
          yarn clean

      - name: Commit and push changes to new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b update-contributors-$(date +%s)

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: update contributors list [skip ci]"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '🔄 chore: update contributors list'
          body: |
            This PR updates the contributors list automatically.
          branch: update-contributors-${{ github.run_id }}
          base: main
          commit-message: 'chore: update contributors list [skip ci]'
          delete-branch: true
