name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for semantic-release to analyze commits

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use your project's Node version

      - name: Install Dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-injected by GitHub
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}        # Only needed if publishing to npm
        run: yarn release